taxi:
   schema-local-storage: ${user.home}/tmp/vyne-test
## In order to use git cloning, uncomment the code below
#taxi:
#   schema-local-storage: C:\gitRemoteTest
   git-schema-repositories:
      -  name: local-gitea
         uri: ssh://git@localhost:222/martypitt/vyne-test.git
         branch: master
         sshPrivateKeyPath: ${user.home}/.ssh/id_rsa
         editable: true
#      -  name: test2
#         uri: git@gitlab.com:devrim.bostanci/remotefileschemas.git
#         branch: master
#         sshPrivateKeyPath: C:\Users\Devrim\.ssh\id_rsa
#         sshPassPhrase: 123456
   git-sync-enabled: true
   git-sync-period-ms: 10000
