taxi:
   project-home: /home/marty/dev/vyne-demos/schema-project
spring:
   application:
      name: file-schema-server
eureka:
   uri: http://127.0.0.1:9022
   client:
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5
vyne:
   schema:
      name: ${spring.application.name}
      version: 0.1.0
server:
   port: 9301

