spring:
   security:
      oauth2:
        resourceserver:
          jwt:
             # Below assumes that an openId-Connect Authorisation server is running at localhost:8080
             # and a 'realm' called 'vyne' setup with it.
             jwk-set-uri: http://localhost:8080/auth/realms/Vyne/protocol/openid-connect/certs
vyne:
   security:
      issuerUrl: http://localhost:8080/auth/realms/Vyne
      clientId: vyne-spa
      scope: openid profile
