taxi:
   schema-local-storage: /path/to/taxonomy
spring:
   application:
      name: file-schema-server
eureka:
   uri: http://127.0.0.1:9022
   client:
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5
vyne:
   schema:
      name: ${spring.application.name}
      version: 0.1.0
      publicationMethod: REMOTE
      pollInterval: 5s
      publishRetryInterval: 3s

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000

server:
   port: 9301

