management.endpoints.web.base-path: /api/actuator
management:
   metrics:
      export:
         prometheus:
            enabled: true
   endpoints:
      web:
         exposure:
            include: prometheus, health, metrics, info, logfile
   endpoint:
      prometheus:
         enabled: true
