spring:
   flyway:
      enabled: true
      url: "jdbc:postgresql://localhost/vyne-query"
      user: vynedb
      password: vynedb
      locations: classpath:db/migration/postgres
   r2dbc:
      url: r2dbc:postgresql://localhost/vyne-query
      username: ${spring.flyway.user}
      password: ${spring.flyway.password}

app:
   query-history:
      enabled: true
