server:
   port: 9022
   compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 1024
   error:
      include-message: always
spring:
   application:
      name: query-service
#   autoconfigure:
#      exclude: org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
   mvc:
      async:
         request-timeout: 18000000
   main:
      banner-mode: off
      web-application-type: reactive
   codec:
      max-in-memory-size: 100MB

   jpa:
      hibernate:
         use-new-id-generator-mappings: false
      #      show-sql: true
      hibernate.ddl-auto: none

      properties:
         hibernate:
            jdbc:
               batch_size: 50
               order_inserts: false

   datasource:
      url: jdbc:h2:file:./vyne-query-analytics;COMPRESS=TRUE;MV_STORE=true;CACHE_SIZE=1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;MODE=LEGACY;DATABASE_TO_LOWER=TRUE
      username: sa
      password:
      driverClassName: org.h2.Driver
      database-platform: org.hibernate.dialect.H2Dialect
      schema: classpath:schema.sql
   security:
      oauth2:
         resourceserver:
            jwt:
               jwk-set-uri: ${vyne.security.open-ipd.jwk-set-uri:''}

#   cloud:
#      discovery:
#         client:
#            simple:
#               instances:
#                  schema-server:
#                     - uri: http://schema-server
vyne:
   newSchemaSubmissionEnabled: true
   data-lineage:
      remoteCalls:
         enabled: falses
   mvc:
      executor:
         corePoolSize: 5
         maxPoolSize: 15
         queueCapacity: 50
   graph:
      vyneGraphBuilderCache:
         baseSchemaCacheSize: 100
         graphWithFactTypesCacheSize: 100
         baseSchemaGraphCacheSize: 100
      vyneDiscoverGraphQuery:
         schemaGraphCacheSize: 5
         searchPathExclusionsCacheSize: 200000
   analytics:
      mode: Inprocess
      persistRemoteCallResponses: false
      persistResults: false
   schema-server:
      url: http://schema-server

   projection:
      distributionMode: LOCAL # One of [LOCAL | DISTRIBUTED] LOCAL = projections are performed on the instance process the query, DISTRIBUTED = distribute projection work to eligible members
      distributionPacketSize: 100 # Number of TypedInstances in a distributed workload - only applicable where distributionMode = DISTRIBUTED
      distributionRemoteBias: 10 # Number of nodes in the hazelcast cluster before work is preferentially distributed to remote nodes

   hazelcast:
      discovery: MULTICAST # One of aws/multicast/swarm
      memberTag: vyne-query-service # Member tags allow delegation of responsibilities
      eurekaUri: http://127.0.0.1:8761/eureka/


   pipelines:
      kibanaUrl: http://localhost:5601/
      logsIndex: 302a6cb0-040f-11ec-a473-775543ab603f
feign:
   hystrix.enabled: false
   client:
      config:
         default:
            connectTimeout: 600000
            readTimeout: 600000

reactive:
   feign:
      hystrix.enabled: false
      client:
         config:
            default:
               options:
                  connectTimeoutMillis: 600000
                  readTimeoutMillis: 600000


logging:
   level:

      org.springframework: WARN
      com.netflix.discovery.InstanceInfoReplicator: ERROR

      #       These two netflix loggers are REALLY noisy - it logs errors on startup, complaining it can't connect .. generally those errors are ignorable
      #        But, in some cases we may care -- so consider turning this back on.
      com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient: OFF
      com.netflix.discovery.DiscoveryClient: OFF
      org.apache.http: OFF
      com.netflix: WARN
      com.hazelcast: WARN
      io.vyne: INFO
#       Enable this to get graph debug schemas:
#      io.vyne.query.GraphSearcher: TRACE
#      io.vyne.query: DEBUG
      org.apache.catalina: WARN
eureka:
   client:
      # You must manually opt-in to Eureka support now
      # eg: by setting eureka.client.enabled=true in the command line
      # options.
      enabled: false
      serviceUrl:
         defaultZone: ${eureka.uri:http://127.0.0.1:8761}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5

management.endpoints.web.base-path: /api/actuator


management:
   metrics:
      export:
         prometheus:
            enabled: false
         influx:
            enabled: false
         elastic:
            enabled: false
         jmx:
            enabled: false
         graphite:
            enabled: false
         datadog:
            enabled: false
         dynatrace:
            enabled: false

   endpoints:
      web:
         exposure:
            include: prometheus,metrics,info,health,logfile,loggers

   endpoint:
      metrics:
         enabled: true
      prometheus:
         enabled: false

