<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <parent>
      <groupId>com.orbitalhq</groupId>
      <artifactId>function-loading</artifactId>
      <version>d0.38.0-SNAPSHOT</version>
   </parent>

   <artifactId>test-java-project</artifactId>

   <dependencies>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>functions-api</artifactId>
         <version>${project.version}</version>
      </dependency>
      <dependency>
         <groupId>com.google.auto.service</groupId>
         <artifactId>auto-service-annotations</artifactId>
         <version>1.1.1</version>
         <scope>provided</scope>
      </dependency>

      <dependency>
         <groupId>com.google.auto.service</groupId>
         <artifactId>auto-service</artifactId>
         <version>1.1.1</version>
         <optional>true</optional>
      </dependency>

   </dependencies>

   <build>
      <plugins>
         <plugin>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-plugin</artifactId>
            <executions>
               <execution>
                  <id>kapt</id>
                  <goals>
                     <goal>kapt</goal>
                  </goals>
                  <configuration>
                     <annotationProcessorPaths>
                        <annotationProcessorPath>
                           <groupId>com.google.auto.service</groupId>
                           <artifactId>auto-service</artifactId>
                           <version>1.1.1</version>
                        </annotationProcessorPath>
                     </annotationProcessorPaths>
                  </configuration>
               </execution>
            </executions>
         </plugin>
      </plugins>
   </build>

</project>
