// THIS FILE IS GENERATED - DO NOT EDIT.
// REGENERATE BY RUNNING IconScssGenerator.generateScssForIcons()
export type IconName = 'ChevronUp' |
  'Gift' |
  'History1' |
  'Password' |
  'Checkout' |
  'Copy' |
  'Loading' |
  'Invite' |
  'Show' |
  'Remove' |
  'Success' |
  'Meeting' |
  'Search' |
  'SoundOff' |
  'Calendar' |
  'Google' |
  'Like' |
  'TextValue' |
  'StarFill' |
  'Upload' |
  'ChevronRight' |
  'Android' |
  'Security' |
  'Warning' |
  'Author' |
  'QuestionHelp' |
  'System' |
  'Call' |
  'Image' |
  'Error' |
  'Apple' |
  'Reminder' |
  'Menu' |
  'SoundOn' |
  'Clear' |
  'Cancel' |
  'Language' |
  'Logout' |
  'Quotation' |
  'Dashboard' |
  'Notification' |
  'Info' |
  'Facebook' |
  'ChevronLeft' |
  'ChevronDown' |
  'CouponFree' |
  'Check' |
  'CreditBankCard' |
  'Filter' |
  'Expand' |
  'LayoutBottom' |
  'Close' |
  'Setting' |
  'Date' |
  'Collapse' |
  'Sort' |
  'Save' |
  'FullScreenOff' |
  'Delete' |
  'Star' |
  'EditProfile' |
  'Q&a' |
  'MarkUnread' |
  'Share' |
  'Time' |
  'History' |
  'Twitter' |
  'CodeEditor' |
  'Bill' |
  'Profile' |
  'Cask' |
  'Graph' |
  'Price' |
  'Menu1' |
  'FilterActive' |
  'FullScreenOn' |
  'LayoutRight' |
  'Add' |
  'MarkRead' |
  'Attributes' |
  'MobilePush' |
  'MoneyTransferEft' |
  'CheckoutCreditCard' |
  'Hide' |
  'Mail' |
  'Reminder1' |
  'Run' |
  'Edit' |
  'Archive' |
  'Sms' |
  'NotificationActive';

export const icons: Record<IconName, string> = {'ChevronUp': 'assets/icons/chevron-up.svg',
  'Gift': 'assets/icons/gift.svg',
  'History1': 'assets/icons/history-1.svg',
  'Password': 'assets/icons/password.svg',
  'Checkout': 'assets/icons/checkout.svg',
  'Copy': 'assets/icons/copy.svg',
  'Loading': 'assets/icons/loading.svg',
  'Invite': 'assets/icons/invite.svg',
  'Show': 'assets/icons/show.svg',
  'Remove': 'assets/icons/remove.svg',
  'Success': 'assets/icons/success.svg',
  'Meeting': 'assets/icons/meeting.svg',
  'Search': 'assets/icons/search.svg',
  'SoundOff': 'assets/icons/sound-off.svg',
  'Calendar': 'assets/icons/calendar.svg',
  'Google': 'assets/icons/google.svg',
  'Like': 'assets/icons/like.svg',
  'TextValue': 'assets/icons/text-value.svg',
  'StarFill': 'assets/icons/star-fill.svg',
  'Upload': 'assets/icons/upload.svg',
  'ChevronRight': 'assets/icons/chevron-right.svg',
  'Android': 'assets/icons/android.svg',
  'Security': 'assets/icons/security.svg',
  'Warning': 'assets/icons/warning.svg',
  'Author': 'assets/icons/author.svg',
  'QuestionHelp': 'assets/icons/question-help.svg',
  'System': 'assets/icons/system.svg',
  'Call': 'assets/icons/call.svg',
  'Image': 'assets/icons/image.svg',
  'Error': 'assets/icons/error.svg',
  'Apple': 'assets/icons/apple.svg',
  'Reminder': 'assets/icons/reminder.svg',
  'Menu': 'assets/icons/menu.svg',
  'SoundOn': 'assets/icons/sound-on.svg',
  'Clear': 'assets/icons/clear.svg',
  'Cancel': 'assets/icons/cancel.svg',
  'Language': 'assets/icons/language.svg',
  'Logout': 'assets/icons/logout.svg',
  'Quotation': 'assets/icons/quotation.svg',
  'Dashboard': 'assets/icons/dashboard.svg',
  'Notification': 'assets/icons/notification.svg',
  'Info': 'assets/icons/info.svg',
  'Facebook': 'assets/icons/facebook.svg',
  'ChevronLeft': 'assets/icons/chevron-left.svg',
  'ChevronDown': 'assets/icons/chevron-down.svg',
  'CouponFree': 'assets/icons/coupon-free.svg',
  'Check': 'assets/icons/check.svg',
  'CreditBankCard': 'assets/icons/credit-bank-card.svg',
  'Filter': 'assets/icons/filter.svg',
  'Expand': 'assets/icons/expand.svg',
  'LayoutBottom': 'assets/icons/layout-bottom.svg',
  'Close': 'assets/icons/close.svg',
  'Setting': 'assets/icons/setting.svg',
  'Date': 'assets/icons/date.svg',
  'Collapse': 'assets/icons/collapse.svg',
  'Sort': 'assets/icons/sort.svg',
  'Save': 'assets/icons/save.svg',
  'FullScreenOff': 'assets/icons/full-screen-off.svg',
  'Delete': 'assets/icons/delete.svg',
  'Star': 'assets/icons/star.svg',
  'EditProfile': 'assets/icons/edit-profile.svg',
  'Q&a': 'assets/icons/q&a.svg',
  'MarkUnread': 'assets/icons/mark-unread.svg',
  'Share': 'assets/icons/share.svg',
  'Time': 'assets/icons/time.svg',
  'History': 'assets/icons/history.svg',
  'Twitter': 'assets/icons/twitter.svg',
  'CodeEditor': 'assets/icons/code-editor.svg',
  'Bill': 'assets/icons/bill.svg',
  'Profile': 'assets/icons/profile.svg',
  'Cask': 'assets/icons/cask.svg',
  'Graph': 'assets/icons/graph.svg',
  'Price': 'assets/icons/price.svg',
  'Menu1': 'assets/icons/menu-1.svg',
  'FilterActive': 'assets/icons/filter-active.svg',
  'FullScreenOn': 'assets/icons/full-screen-on.svg',
  'LayoutRight': 'assets/icons/layout-right.svg',
  'Add': 'assets/icons/add.svg',
  'MarkRead': 'assets/icons/mark-read.svg',
  'Attributes': 'assets/icons/attributes.svg',
  'MobilePush': 'assets/icons/mobile-push.svg',
  'MoneyTransferEft': 'assets/icons/money-transfer-eft.svg',
  'CheckoutCreditCard': 'assets/icons/checkout-credit-card.svg',
  'Hide': 'assets/icons/hide.svg',
  'Mail': 'assets/icons/mail.svg',
  'Reminder1': 'assets/icons/reminder-1.svg',
  'Run': 'assets/icons/run.svg',
  'Edit': 'assets/icons/edit.svg',
  'Archive': 'assets/icons/archive.svg',
  'Sms': 'assets/icons/sms.svg',
  'NotificationActive': 'assets/icons/notification-active.svg'};
