spring:
   application:
      name: pipeline-jet-runner
   main:
      web-application-type: reactive
      banner-mode: off
   codec:
      max-in-memory-size: 100MB
   autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
   cloud:
      config:
         enabled: false

server:
   port: 9615
   error:
      include-message: always

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000


vyne:
   graph:
      vyneGraphBuilderCache:
         baseSchemaCacheSize: 100
         graphWithFactTypesCacheSize: 100
         baseSchemaGraphCacheSize: 100
      vyneDiscoverGraphQuery:
         schemaGraphCacheSize: 5
         searchPathExclusionsCacheSize: 200000
   pipelines:
      query-mode: EMBEDDED


management:
   prometheus:
      metrics:
         export:
            enabled: false
   influx:
      metrics:
         export:
            enabled: false
   dynatrace:
      metrics:
         export:
            enabled: false
   datadog:
      metrics:
         export:
            enabled: false
   elastic:
      metrics:
         export:
            enabled: false
   jmx:
      metrics:
         export:
            enabled: false
   graphite:
      metrics:
         export:
            enabled: false


   endpoints:
      web:
         exposure:
            include: prometheus,metrics,info,health,logfile,loggers
         base-path: /api/actuator

   endpoint:
      metrics:
         enabled: true
      prometheus:
         enabled: false
      health:
         show-components: always
         show-details: always
logging:
   level:
      io.vyne: INFO
      us.fatehi.utility.scheduler: WARN
      schemacrawler.crawl: WARN
      schemacrawler.loader.attributes: WARN
      schemacrawler.loader.weakassociations: WARN
      schemacrawler.loader.counts: WARN
      schemacrawler.tools.utility: WARN
