spring:
   application:
      name: pipeline-jet-runner
   main:
      web-application-type: reactive
      banner-mode: off
   codec:
      max-in-memory-size: 100MB
   autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

server:
   port: 9615
   error:
      include-message: always

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000

eureka:
   uri: http://127.0.0.1:8761
   client:
      ## Eureka client must be enabled explicitly
      enabled: false
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5

vyne:
   # Use consistent naming across all Vyne components.
   # Check docs/content/deployment/README.mdx
   query-service:
      name: query-service
      url: http://vyne
   graph:
      vyneGraphBuilderCache:
         baseSchemaCacheSize: 100
         graphWithFactTypesCacheSize: 100
         baseSchemaGraphCacheSize: 100
      vyneDiscoverGraphQuery:
         schemaGraphCacheSize: 5
         searchPathExclusionsCacheSize: 200000


management.endpoints.web.base-path: /api/actuator


management:
   metrics:
      export:
         prometheus:
            enabled: false
         influx:
            enabled: false
         elastic:
            enabled: false
         jmx:
            enabled: false
         graphite:
            enabled: false
         datadog:
            enabled: false
         dynatrace:
            enabled: false

   endpoints:
      web:
         exposure:
            include: prometheus,metrics,info,health,logfile,loggers

   endpoint:
      metrics:
         enabled: true
      prometheus:
         enabled: false

