<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <parent>
      <groupId>com.orbitalhq</groupId>
      <artifactId>connectors</artifactId>
      <version>0.36.0-M9</version>
   </parent>

   <artifactId>hazelcast-connector</artifactId>

   <properties>
      <maven.compiler.source>17</maven.compiler.source>
      <maven.compiler.target>17</maven.compiler.target>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
   </properties>

   <dependencies>
      <!-- TaxiQL query engine needed for access to caching primitives.
      We may want to split these out at some point -->

      <dependency>
         <groupId>com.hazelcast</groupId>
         <artifactId>hazelcast</artifactId>
      </dependency>
      <dependency>
         <groupId>com.hazelcast</groupId>
         <artifactId>hazelcast</artifactId>
         <version>${hazelcast.version}</version>
         <classifier>tests</classifier>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>schema-consumer-api</artifactId>
         <version>${project.version}</version>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>connectors-core</artifactId>
         <version>${project.version}</version>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>vyne-core-types</artifactId>
         <version>${project.version}</version>
      </dependency>
      <dependency>
         <groupId>io.projectreactor.kotlin</groupId>
         <artifactId>reactor-kotlin-extensions</artifactId>
      </dependency>
      <dependency>
         <groupId>app.cash.turbine</groupId>
         <artifactId>turbine-jvm</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>taxiql-query-engine</artifactId>
         <version>${project.version}</version>
         <type>test-jar</type>
         <scope>test</scope>
         <exclusions>
            <exclusion>
               <artifactId>log4j-to-slf4j</artifactId>
               <groupId>org.apache.logging.log4j</groupId>
            </exclusion>
         </exclusions>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>taxiql-query-engine</artifactId>
         <version>${project.version}</version>
         <exclusions>
            <exclusion>
               <artifactId>log4j-to-slf4j</artifactId>
               <groupId>org.apache.logging.log4j</groupId>
            </exclusion>
         </exclusions>
      </dependency>

      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>vyne-core-types</artifactId>
         <version>${project.version}</version>
         <scope>test</scope>
         <type>test-jar</type>
      </dependency>

      <!-- https://mvnrepository.com/artifact/ch.qos.logback/logback-core -->
      <dependency>
         <groupId>ch.qos.logback</groupId>
         <artifactId>logback-core</artifactId>
         <version>1.4.12</version>
         <scope>test</scope>
      </dependency>

      <dependency>
         <groupId>ch.qos.logback</groupId>
         <artifactId>logback-classic</artifactId>
         <version>1.4.12</version>
         <scope>test</scope>
      </dependency>

   </dependencies>
</project>
