spring:
   application:
      name: vyne-analytics-server
   main:
      banner-mode: off
      web-application-type: reactive
   codec:
      max-in-memory-size: 100MB

   flyway:
      enabled: false

   cloud.config.enabled: false

   jpa:
      hibernate:
         use-new-id-generator-mappings: false
         ddl-auto: none

      properties:
         hibernate:
            jdbc:
               batch_size: 50
               order_inserts: false
      database-platform: org.hibernate.dialect.H2Dialect

   datasource:
      url: jdbc:h2:file:./vyne-query-analytics;COMPRESS=TRUE;MV_STORE=true;CACHE_SIZE=1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;MODE=LEGACY;DATABASE_TO_LOWER=TRUE
      username: sa
      password:
      driverClassName: org.h2.Driver
   sql:
      init:
         schema-locations: classpath:schema-h2.sql
         mode: embedded

server:
   port: 9405

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000

vyne:
   analytics:
      persistRemoteCallResponses: true
      persistResults: true
   analytics-server:
      port: 7654

# Actuators + prometheus metrics configuration

management.endpoints.web.base-path: /api/actuator
