spring:
   application:
      name: vyne-analytics-server
   main:
      banner-mode: off
      web-application-type: reactive
   codec:
      max-in-memory-size: 100MB

   flyway:
      enabled: false

   cloud.config.enabled: false

   jpa:
      hibernate:
         use-new-id-generator-mappings: false
         ddl-auto: none

      properties:
         hibernate:
            jdbc:
               batch_size: 50
               order_inserts: false
      database-platform: org.hibernate.dialect.H2Dialect

   datasource:
      url: jdbc:h2:file:./vyne-query-analytics;COMPRESS=TRUE;MV_STORE=true;CACHE_SIZE=1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;MODE=LEGACY;DATABASE_TO_LOWER=TRUE
      username: sa
      password:
      driverClassName: org.h2.Driver
   sql:
      init:
         schema-locations: classpath:schema.sql
         mode: always

server:
   port: 9405

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000
eureka:
   uri: http://127.0.0.1:8761
   client:
      # Eureka must be enabled explicitly
      enabled: false
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5
      metadata-map:
         vyne-analytics-port: ${vyne.analytics-server.port}

vyne:
   history:
      persistRemoteCallResponses: true
      persistResults: true
   analytics-server:
      port: 7654

# Actuators + prometheus metrics configuration

management.endpoints.web.base-path: /api/actuator
management:
   metrics:
      export:
         prometheus:
            enabled: false
         influx:
            enabled: false
         elastic:
            enabled: false
         jmx:
            enabled: false
         graphite:
            enabled: false
         datadog:
            enabled: false
         dynatrace:
            enabled: false

   endpoint:
      metrics:
         enabled: true
      prometheus:
         enabled: false

   endpoints:
      web:
         exposure:
            include: prometheus,metrics,info,health
