spring:
   application:
      name: vyne-analytics-server
   main:
      banner-mode: off
      web-application-type: reactive
   codec:
      max-in-memory-size: 100MB

   cloud.config.enabled: false

   flyway:
      enabled: true
      url: ${spring.datasource.url}
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}
      locations: classpath:db/postgres

   datasource:
      url: jdbc:postgresql://${vyne.db.host}:${vyne.db.port:5432}/${vyne.db.database:orbital}
      username: ${vyne.db.username}
      password: ${vyne.db.password}
      driver-class-name: org.postgresql.Driver

server:
   port: 9405

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000

vyne:
   analytics:
      persistRemoteCallResponses: true
      persistResults: true
   analytics-server:
      port: 7654

# Actuators + prometheus metrics configuration

management.endpoints.web.base-path: /api/actuator
