variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -U"
#  MAVEN_CLI_OPTS: "--show-version"

stages:
   - build
   - deploy

build-jvm:
  stage: build
  cache:
     paths:
        - .m2/repository
     key: "maven-$CI_COMMIT_REF_SLUG"
  script:
    - 'mvn $MAVEN_CLI_OPTS clean test-compile jar:test-jar install -Dskip.npm -PrunBenchmarkTests'
  artifacts:
    paths:
       - "*/target"
    expire_in: 1 hours
    reports:
      junit:
      # Note:This won't actually work, b/c of https://gitlab.com/gitlab-org/gitlab-runner/issues/2620
      # However, leaving this here to pick up later
        - "*/target/surefire-reports/TEST-*.xml"

build-ui:
   stage: build
   cache:
      paths:
         - vyne-query-service/src/main/web/node
      key: "node-$CI_COMMIT_REF_SLUG"
   script:
      # Only build the frontend. Nothing JVM related
      - 'mvn $MAVEN_CLI_OPTS -DskipTests frontend:install-node-and-npm frontend:npm@run-npm-install frontend:npm@ng-build -f vyne-query-service/pom.xml'
   artifacts:
      paths:
         - "vyne-query-service/target/classes/static"
      expire_in: 1 hours

publish-snapshot:
  stage: deploy
  script:
    - docker login -u vynecd -p $DOCKER_HUB_PASSWORD
    - 'mvn $MAVEN_CLI_OPTS -DskipTests -Dskip.npm deploy -P snapshot-releases ' # Skip UI and tests. Already there from previous stages and artifacts
  only:
    - develop


publish-release:
  stage: deploy
  script:
    - docker login -u vynecd -p $DOCKER_HUB_PASSWORD
    - 'mvn $MAVEN_CLI_OPTS -DskipTests -Dskip.npm release:prepare release:perform'
  only:
    - master

