include:
   -  template: Terraform/Base.gitlab-ci.yml

variables:
   # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
   # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
   MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
   # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
   # when running from the command line.
   # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
   MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -U"
   # Used during gitflow interaction.
   MAJOR_RELEASE_DIGIT: 0
   MINOR_RELEASE_DIGIT: 1
   PATCH_RELEASE_DIGIT: 2

   TF_STATE_NAME_DEV: dev
   TF_STATE_NAME_PROD: prod

.git_template: &git_setup |
   git remote set-url --push origin "https://oauth2:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
   git config user.name "vyne-cd"
   git config user.email vyne-cd@vyne.co

stages:
   - build
   - deploy
   - verify
   - release

default:
   tags:
      - docker

snyk:
   stage: verify
   image:
      name: snyk/snyk:maven-3-jdk-11
      entrypoint: [ "" ]
   variables:
      DOCKER_HOST: tcp://docker:2375/
      DOCKER_TLS_CERTDIR: "" # Instruct Docker not to start over TLS.
      DOCKER_DRIVER: overlay2
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      PROGRESS_NO_TRUNC: 1
      SNYK_TOKEN: $SNYK_TOKEN
   services:
      -  name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10.21-dind
         alias: docker
         command: [ "--tls=false" ]
   #   before_script:
   #      - echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
   script:
      - snyk auth
      - "snyk container test ${CI_REGISTRY_IMAGE}/schema-server:0.22.0-SNAPSHOT-BETA-693d6f62"
