variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
#  MAVEN_CLI_OPTS: "--show-version"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
  paths:
    - .m2/repository
    - vyne-query-service/src/main/web/node_modules
    - vyne-query-service/node
    - vyne-query-service/src/main/web/.npm
  key: "$CI_JOB_REF_NAME"

stages:
   - build
   - deploy

build-web:
#  image: trion/ng-cli:7.3.9
  stage: build
  script:
    - cd vyne-query-service/src/main/web
    - npm ci --cache .npm --prefer-offline
    - npm run-script build-prod
  artifacts:
    paths:
      - vyne-query-service/target/classes/static

build-jvm:
#  image: maven:3.6.3-jdk-8
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS clean install'
  artifacts:
    reports:
      junit:
      # Note:This won't actually work, b/c of https://gitlab.com/gitlab-org/gitlab-runner/issues/2620
      # However, leaving this here to pick up later
        - "*/target/surefire-reports/TEST-*.xml"
#  except:
#    - develop
#    - master

publish-snapshot:
#  image: maven:3.6.3-jdk-8
  stage: deploy
  script:
    - docker login -u vynecd -p $DOCKER_HUB_PASSWORD
#    -don't need to run tests as they were run in the previous stage
    - 'mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true deploy'
  artifacts:
    reports:
      junit:
      # Note:This won't actually work, b/c of https://gitlab.com/gitlab-org/gitlab-runner/issues/2620
      # However, leaving this here to pick up later
        - "*/target/surefire-reports/TEST-*.xml"
  only:
    - develop

publish-release:
#  image: maven:3.6.3-jdk-8
  stage: deploy
  script:
    - docker login -u vynecd -p $DOCKER_HUB_PASSWORD
    - 'mvn $MAVEN_CLI_OPTS release:prepare release:perform'
  artifacts:
    reports:
      junit:
      # Note:This won't actually work, b/c of https://gitlab.com/gitlab-org/gitlab-runner/issues/2620
      # However, leaving this here to pick up later
        - "*/target/surefire-reports/TEST-*.xml"
  only:
    - master

