# Local Vyne setup
#
# How to start
# - docker-compose pull # to pull latest snapshot images
# - docker-compose up   # to start the stack locally
#
# How to stop
# - ctrl+c or
# - docker-compose down
#
# Note: Remember to update your file-schema-server volume to point to your file system where you keep your *.taxi files
version: "3.4"
services:
   vyne:
      image: vyneco/vyne:latest-snapshot
      ports:
         - 5701-5721
         - 9022:9022
      environment:
         PROFILE: embedded-discovery
         OPTIONS: --vyne.schema.publicationMethod=DISTRIBUTED

   file-schema-server:
      image: vyneco/file-schema-server:latest-snapshot
      ports:
         - 5701-5721
      volumes:
         # Sample path in this project
         - ./schemas:/var/lib/vyne/schemas
         # Sample path on windows machine
         #- /C/dev/workspace/taxonomy:/var/lib/vyne/schemas
      environment:
         OPTIONS: --taxi.schema-local-storage=/var/lib/vyne/schemas --eureka.uri=http://vyne:9022 --vyne.schema.publicationMethod=DISTRIBUTED

   cask:
      image: vyneco/cask:latest-snapshot
      depends_on:
         - vyne
      environment:
         PROFILE: local
         OPTIONS: --eureka.uri=http://vyne:9022 --vyne.schema.publicationMethod=DISTRIBUTED
      ports:
         - 5701-5721
         - 5432:5432
         - 8800:8800
