version: 3.8
services:
   vyne:
      image: vyneco/vyne
      environment:
         PROFILE: embedded-discovery

   file-schema-server:
      image: vyneco/file-schema-server
      volumes:
      -  ./schemas:/var/lib/postgresql/data
      environment:
         OPTIONS: --Dtaxi.project-home=/var/lib/vyne/schemas
