# Global Gradle properties
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true

# Java
java.version=21

# Build properties
buildNumber=0
version=0.36.0-SNAPSHOT

# External properties (set via environment or command line)
# JOOQ_REPO_USERNAME=
# JOOQ_REPO_PASSWORD=