server:
  port: 9022
spring:
  application:
    name: query-service
logging:
  level:
      org.springframework: WARN
      com.netflix.discovery.InstanceInfoReplicator: ERROR

#       These two netflix loggers are REALLY noisy - it logs errors on startup, complaining it can't connect .. generally those errors are ignorable
#        But, in some cases we may care -- so consider turning this back on.
      com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient: OFF
      com.netflix.discovery.DiscoveryClient: OFF

      com.netflix: WARN
      com.hazelcast: WARN
      io.vyne: DEBUG
      org.apache.catalina: WARN
eureka:
   client:
#      registryFetchIntervalSeconds: 1
#      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri:http://127.0.0.1:8761}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5
