server:
  port: 9022
spring:
  application:
    name: query-service
vyne:
   schemaStore:
      name: discovery
logging:
  level:
      io.vyne: DEBUG
      io.osmosis: DEBUG
eureka:
   client:
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri:http://127.0.0.1:8761}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5
