server:
  port: 9022
spring:
  application:
    name: query-service
logging:
  level:
      org.springframework: WARN
      com.netflix: WARN
      com.hazelcast: WARN
      io.vyne: DEBUG
      org.apache.catalina: WARN
eureka:
   client:
#      registryFetchIntervalSeconds: 1
#      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri:http://127.0.0.1:8761}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5
