spring:
  application:
    name: clients
eureka:
   client:
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri:http://127.0.0.1:8761}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5
polymer:
   schemaStore:
      name: discovery
   schema:
      name: clients
      version: 0.1.0
logging:
  level:
      io.polymer: DEBUG
      io.osmosis: DEBUG
      feign.Logger: DEBUG

ribbon:
   restclient:
      enabled: true
   ServerListRefreshInterval: 1000
server:
  port: 9029
