server:
   port: 9500
   http2:
      enabled: true
   compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 1024
   error:
      include-message: always

hubspot:
   api:
      url: https://api.hubapi.com
      auth-token:
   subscriptions:
      voyager-updates-id:
      general-marketing:

spring:
   web:
      resources:
         cache:
            use-last-modified: on
            cachecontrol:
               no-transform: true
               must-revalidate: true


management:
   endpoints:
      web:
         exposure:
            include: health
         base-path: /api/actuator
