<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <parent>
      <groupId>com.orbitalhq</groupId>
      <artifactId>platform</artifactId>
      <version>0.34.0-SNAPSHOT</version>
   </parent>

   <artifactId>avro-message-format</artifactId>

   <properties>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
   </properties>

   <dependencies>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>vyne-core-types</artifactId>
         <version>${project.version}</version>
      </dependency>
      <!-- Confluent seem to have their own "special" flavour of Avro, which encodes additional bytes
      at the beginning. FFS:

      "The Confluent Schema Registry based Avro serializer, by design, does not include
       the message schema; but rather, includes the schema ID (in addition to a magic byte)
       followed by the normal binary encoding of the data itself."
      -->
      <!-- https://mvnrepository.com/artifact/io.confluent/kafka-avro-serializer -->
      <dependency>
         <groupId>io.confluent</groupId>
         <artifactId>kafka-avro-serializer</artifactId>
         <version>7.6.0</version>
      </dependency>


      <dependency>
         <groupId>org.taxilang</groupId>
         <artifactId>avro-to-taxi</artifactId>
         <version>${taxi.version}</version>
      </dependency>

   </dependencies>
   <repositories>
      <repository>
         <id>confluent</id>
         <url>https://packages.confluent.io/maven/</url>
      </repository>
   </repositories>

</project>
