server:
   error.include-message: always
   port: 8800

spring.datasource:
   url: "jdbc:postgresql://localhost:5432/vynedb"
   username: "vynedb"
   password: "vynedb"
   driver: "org.postgresql.Driver"
   hikari:
     maximum-pool-size: 20


spring:
   main:
      banner-mode: off
      web-application-type: reactive
   application:
      name: cask
   flyway:
      url: ${spring.datasource.url}
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}
      enabled: true
      locations: classpath:db/migration
   codec:
      max-in-memory-size: 1024MB

   jdbc:
      template:
         fetch-size: 100
   cloud:
      config:
         enabled: false

eureka:
   uri: http://127.0.0.1:8761
   client:
      enabled: false
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5

vyne:
   schema-server:
      url: http://schema-server

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000

hystrix:
   command:
      default:
         execution.isolation.thread.timeoutInMilliseconds: 10000

reactive:
   feign:
      hystrix.enabled: false
      client:
         config:
            default:
               options:
                  connectTimeoutMillis: 600000
                  readTimeoutMillis: 600000

cask:
   maxTextMessageBufferSize: 67108864 # 1024 * 1024 * 64
   maxBinaryMessageBufferSize: 67108864 # 1024 * 1024 * 64
   eviction.cron: 0 0 * * * * # on the hour every hour
   service:
      annotations: Datasource
   streamQueries:
      enabled: true

   dispatcher:
      queryDispatcherPoolSize: 50


# Actuators + prometheus metrics configuration

management.endpoints.web.base-path: /api/actuator

management:
   metrics:
      export:
         prometheus:
            enabled: false
         influx:
            enabled: false
         elastic:
            enabled: false
         jmx:
            enabled: false
         graphite:
            enabled: false
         datadog:
            enabled: false
         dynatrace:
            enabled: false

   endpoint:
      metrics:
         enabled: true
      prometheus:
         enabled: false

      logfile:
         enabled: true
         external-file: logs/cask.log

   endpoints:
      web:
         exposure:
            include: prometheus,metrics,info,health,logfile


