server:
   error.include-message: always
   port: 8800
spring.kafka.consumer:
   group-id: "cask"
   auto-offset-reset: "earliest"

spring.datasource:
   url: "jdbc:postgresql://localhost:5432/vynedb"
   username: "vynedb"
   password: "vynedb"
   driver: "org.postgresql.Driver"
   hikari:
     maximum-pool-size: 20

spring:
   main:
      web-application-type: reactive
   application:
      name: cask
   flyway:
      url: ${spring.datasource.url}
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}
      enabled: true

      locations: classpath:db/migration

eureka:
   uri: http://127.0.0.1:9022
   client:
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5

vyne:
   queryService:
      name: query-service
   queryServiceUrl: http://${vyne.queryService.name}
   schema:
      publicationMethod: REMOTE
      pollInterval: 5s
      publishRetryInterval: 3s

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000

cask:
   maxTextMessageBufferSize: 67108864 # 1024 * 1024 * 64
   maxBinaryMessageBufferSize: 67108864 # 1024 * 1024 * 64
   views:
      -  typeName: ion.orders.OrderEvent
         distinct: true
         inherits:
            - cacib.orders.OrderLifecycleEvent
         join:
            kind: LEFT_OUTER
            left: ion.orders.Order
            right: ion.trade.Trade
            joinOn:
               -  leftField: orderId
                  rightField: orderId
               -  leftField: lastTradeDate
                  rightField: tradeCreationDate
               -  leftField: lastTradeTime
                  rightField: tradeCreationTime
   service:
      annotations: Datasource

# Actuators + prometheus metrics configuration
management:
   endpoint:
      metrics:
         enabled: true
      prometheus:
         enabled: true
      logfile:
         enabled: true
         external-file: logs/cask.log
   endpoints:
      web:
         exposure:
            include: prometheus,metrics,info,health,logfile
   metrics:
      export:
         prometheus:
            enabled: true
