# curl -XGET http://localhost:9022/api/actuator/prometheus
management:
   metrics:
      export:
        prometheus:
           enabled: true

   endpoints:
      web:
         exposure:
            include: prometheus

   endpoint:
      prometheus:
         enabled: false