spring:
   kafka:
      consumer:
         bootstrap-servers: localhost:9092
         group-id: "cask"
         auto-offset-reset: earliest

cask:
   kafka:
      enabled: true
      topic: foo
      type-name: com.cacib.m2m.Dummy

