spring:
   kafka:
      consumer:
         bootstrap-servers: localhost:9092
         group-id: vynemon1
         auto-offset-reset: earliest


cask:
   kafka:
      enabled: true
      topic: otc-swap-2
      consumer-count: 6
      type-name: Swap
      # json or xml
      ingestion-type: xml


