# this is a sample schema file for a user object.

---
initial_entries: 10
randomize: false
item_id: _uuid_
name: _firstname_ _lastname_
description: _activity_
icon: _icon_
created:  _itemtimestamp_
...
