package com.orbitalhq.copilot.refiner

import com.orbitalhq.query.planner.QueryPlanner
import com.orbitalhq.query.planner.TaxiQlRewriter
import com.orbitalhq.schemas.Schema
import lang.taxi.query.TaxiQlQuery

/**
 * Modifies queries generated by OpenAI, and applies a set of processing to them.
 * This is useful for rules that are easier for us to enforce (eg., "Always apply caching when you call services"), but harder
 * for OpenAI to apply without burning through context tokens
 */
class GeneratedQueryRefiner(
   val rules: List<QueryRefinerRule> = DEFAULT_RULES
) {
   companion object {
      val DEFAULT_RULES = listOf(
         ApplyCachingIfServicesInvolved,
         ApplyStateStoreIfMultipleStreamsInvolved
      )
   }

   fun apply(query: TaxiQlQuery, querySchema: Schema): Pair<TaxiQlQuery, Schema> {
      val queryPlanner = QueryPlanner()
      val rewriter = TaxiQlRewriter()
      return rules.fold(query to querySchema) { (query,querySchema), rule ->
         rule.apply(query, querySchema, queryPlanner, rewriter)
      }
   }
}

interface QueryRefinerRule {
   fun apply(
      query: TaxiQlQuery,
      querySchema: Schema,
      queryPlanner: QueryPlanner,
      queryRewriter: TaxiQlRewriter
   ): Pair<TaxiQlQuery, Schema>
}

object ApplyStateStoreIfMultipleStreamsInvolved : QueryRefinerRule {
   override fun apply(
      query: TaxiQlQuery,
      querySchema: Schema,
      queryPlanner: QueryPlanner,
      queryRewriter: TaxiQlRewriter
   ): Pair<TaxiQlQuery, Schema> {
      val metadata = queryPlanner.buildMetadata(query, querySchema)
      if (metadata.minimumStreamOperations.size > 1) {
         val amended = queryRewriter.appendQueryAnnotationIfNotPresent(query.source, "@StateStore")
         return if (amended != query.source) {
            val (updatedQuery, _, updatedSchema) = querySchema.parseQuery(amended)
            updatedQuery to updatedSchema
         } else {
            query to querySchema
         }
      } else return query to querySchema
   }

}

object ApplyCachingIfServicesInvolved : QueryRefinerRule {
   override fun apply(
      query: TaxiQlQuery,
      querySchema: Schema,
      queryPlanner: QueryPlanner,
      queryRewriter: TaxiQlRewriter
   ): Pair<TaxiQlQuery, Schema> {
      val metadata = queryPlanner.buildMetadata(query, querySchema)
      if (metadata.allCandidateOperations.isNotEmpty()) {
         val amended = queryRewriter.appendQueryAnnotationIfNotPresent(query.source, "@Cache")
         return if (amended != query.source) {
            val (updatedQuery, _, updatedSchema) = querySchema.parseQuery(amended)
            updatedQuery to updatedSchema
         } else {
            query to querySchema
         }
      } else return query to querySchema
   }

}
