version: '3.7'

services:
   prometheus:
      image: prom/prometheus:v2.44.0
      network_mode: host
      ports:
         - "9090:9090"
      expose:
         - 9090
      volumes:
         - ./prometheus.yml:/etc/prometheus/prometheus.yml

   grafana:
      image: grafana/grafana:11.5.2
      network_mode: host
      container_name: grafana
      ports:
         - "3000:3000"
      restart: unless-stopped
      volumes:
         - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
