<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <parent>
      <groupId>com.orbitalhq</groupId>
      <artifactId>nosql-connectors</artifactId>
      <version>0.36.0-M9</version>
   </parent>

   <artifactId>mongodb-connector</artifactId>

   <dependencies>
      <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-data-mongodb-reactive</artifactId>
      </dependency>

      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>connectors-core</artifactId>
         <version>${project.version}</version>
      </dependency>

      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>schema-api</artifactId>
         <version>${project.version}</version>
      </dependency>

      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>utils</artifactId>
         <version>${project.version}</version>
      </dependency>

      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>vyne-core-types</artifactId>
         <version>${project.version}</version>
      </dependency>

      <dependency>
         <groupId>org.testcontainers</groupId>
         <artifactId>testcontainers</artifactId>
         <scope>test</scope>
      </dependency>

      <dependency>
         <groupId>org.testcontainers</groupId>
         <artifactId>junit-jupiter</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>io.projectreactor</groupId>
         <artifactId>reactor-test</artifactId>
         <scope>test</scope>
      </dependency>

      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>taxiql-query-engine</artifactId>
         <version>${project.version}</version>
         <type>test-jar</type>
         <scope>test</scope>
         <exclusions>
            <exclusion>
               <artifactId>log4j-to-slf4j</artifactId>
               <groupId>org.apache.logging.log4j</groupId>
            </exclusion>
         </exclusions>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>taxiql-query-engine</artifactId>
         <version>${project.version}</version>
         <scope>test</scope>
         <exclusions>
            <exclusion>
               <artifactId>log4j-to-slf4j</artifactId>
               <groupId>org.apache.logging.log4j</groupId>
            </exclusion>
         </exclusions>
      </dependency>

      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>vyne-core-types</artifactId>
         <version>${project.version}</version>
         <scope>test</scope>
         <type>test-jar</type>
      </dependency>
   </dependencies>

</project>
