<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <parent>
      <artifactId>platform</artifactId>
      <groupId>com.orbitalhq</groupId>
      <version>d0.38.0-SNAPSHOT</version>
   </parent>
   <modelVersion>4.0.0</modelVersion>

   <artifactId>vyne-csv-utils</artifactId>


   <licenses>
      <license>
         <name>The Apache Software License, Version 2.0</name>
         <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      </license>
   </licenses>

   <dependencies>
      <dependency>
         <groupId>com.fasterxml.jackson.module</groupId>
         <artifactId>jackson-module-kotlin</artifactId>
      </dependency>
      <dependency>
         <groupId>com.fasterxml.jackson.core</groupId>
         <artifactId>jackson-databind</artifactId>
      </dependency>
      <dependency>
         <groupId>com.fasterxml.jackson.dataformat</groupId>
         <artifactId>jackson-dataformat-xml</artifactId>
      </dependency>
      <dependency>
         <groupId>org.taxilang</groupId>
         <artifactId>xsd2taxi</artifactId>
         <version>${taxi.version}</version>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>vyne-core-types</artifactId>
         <version>${project.version}</version>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>vyne-core-types</artifactId>
         <version>${project.version}</version>
         <scope>test</scope>
         <type>test-jar</type>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>test-utils</artifactId>
         <version>${project.version}</version>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>datatype-converters</artifactId>
         <version>d0.38.0-SNAPSHOT</version>
         <scope>test</scope>
      </dependency>

      <dependency>
         <groupId>org.taxilang</groupId>
         <artifactId>lang-to-taxi-api</artifactId>
         <version>${taxi.version}</version>
      </dependency>

      <dependency>
         <groupId>org.taxilang</groupId>
         <artifactId>compiler</artifactId>
         <type>test-jar</type>
         <version>${taxi.version}</version>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>org.taxilang</groupId>
         <artifactId>taxi-annotations</artifactId>
         <version>${taxi.version}</version>
      </dependency>
      <dependency>
         <groupId>org.taxilang</groupId>
         <artifactId>compiler</artifactId>
         <version>${taxi.version}</version>
      </dependency>
      <dependency>
         <groupId>org.taxilang</groupId>
         <artifactId>taxi-stdlib-annotations</artifactId>
         <version>${taxi.version}</version>
      </dependency>

      <dependency>
         <groupId>org.taxilang</groupId>
         <artifactId>taxi-jvm-common</artifactId>
         <version>${taxi.version}</version>
      </dependency>

      <dependency>
         <groupId>org.taxilang</groupId>
         <artifactId>compiler</artifactId>
         <version>${taxi.version}</version>
      </dependency>

      <dependency>
         <groupId>org.jetbrains.kotlinx</groupId>
         <artifactId>dataframe</artifactId>
         <version>${kotlin.dataframe.version}</version>
         <exclusions>
            <exclusion>
               <groupId>org.slf4j</groupId>
               <artifactId>slf4j-simple</artifactId>
            </exclusion>
            <exclusion>
               <!-- mariadb is LGPL - we don't use this, so lets exclude -->
               <groupId>org.mariadb.jdbc</groupId>
               <artifactId>mariadb-java-client</artifactId>
            </exclusion>
         </exclusions>
      </dependency>
   </dependencies>

   <dependencyManagement>
      <dependencies>
         <dependency>
            <!-- Causes runtime failures with Spring Boot:
             LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.simple.SimpleLoggerFactory loaded from file ...
             -->
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.16</version>
            <scope>runtime</scope>
            <exclusions>
               <exclusion>
                  <groupId>*</groupId>
                  <artifactId>*</artifactId>
               </exclusion>
            </exclusions>
         </dependency>
      </dependencies>
   </dependencyManagement>

</project>
