server:
  port: 8824
spring:
  application:
    name: hello-world
vyne:
   schemaStore:
      name: discovery
   schema:
      name: hello-world
      version: 0.1.0
logging:
  level:
      io.vyne: DEBUG
      io.osmosis: DEBUG
ribbon:
   restclient:
      enabled: true
   ServerListRefreshInterval: 1000
