spring:
   datasource:
      driver: "org.postgresql.Driver"
      driverClassName: org.postgresql.Driver
   sql:
      init:
         mode: never
   flyway:
      enabled: true
      locations: classpath:db/postgres
orbital:
   cors:
      enabled: false
