management:
   endpoint:
      metrics:
         enabled: true
   endpoints:
      web:
         exposure:
            include: '*'

spring:
   datasource:
      url: "jdbc:postgresql://localhost:5432/orbital-station"
      username: "martypitt"
      password: "password"
      driver: "org.postgresql.Driver"
      driverClassName: org.postgresql.Driver
   sql:
      init:
         mode: never
   flyway:
      enabled: true
#      locations: classpath:db/postgres
orbital:
   cors:
      enabled: false
