management:
   endpoint:
      metrics:
         enabled: true
   endpoints:
      web:
         exposure:
            include: '*'

spring:
   datasource:
      url: jdbc:h2:mem:orbital
      username: sa
      password: password
      driverClassName: org.h2.Driver
   jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
   flyway:
      enabled: false
