server:
   port: 9022
   error:
      whitelabel:
         enabled: false
      include-message: always
   compression:
      enabled: true
      mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
      min-response-size: 1024
spring:
   codec:
      max-in-memory-size: 10MB
   main:
      web-application-type: reactive
   cloud:
      config:
         import-check:
            enabled: false
   datasource:
      url: jdbc:postgresql://${vyne.db.host}:${vyne.db.port:5432}/${vyne.db.database:orbital}?ApplicationName=${spring.application.name}
      username: ${vyne.db.username}
      password: ${vyne.db.password}
      driver-class-name: org.postgresql.Driver
      hikari:
         connection-timeout: ${vyne.db.datasource.connectionTimeout:30000} #default is 30 seconds (specified in milliseconds)
         max-lifetime: ${vyne.db.datasource.maxLifetime:1800000} # default is 30 minutes (specified in milliseconds)
         idle-timeout: ${vyne.db.datasource.idleTimout:600000} # default is 60 minutes (specified in milliseconds)
         minimum-idle: ${vyne.db.datasource.minimumIdle:10} # default is 10
         maximum-pool-size: ${vyne.db.datasource.maxPoolSize:10} # default is 10
   sql:
      init:
         mode: never
   application:
      name: orbital-station
   flyway:
      enabled: ${vyne.db.enabled}
      locations: classpath:db/migration
   web:
      resources:
         cache:
            use-last-modified: on
            cachecontrol:
               no-transform: true
               must-revalidate: true

management:
   endpoint:
     prometheus:
        enabled: true
   endpoints:
      web:
         exposure:
            include: prometheus,metrics,info,health,logfile,loggers
         base-path: /api/actuator
vyne:
   db:
      enabled: true
   schema:
      consumer:
         method: local
      publisher:
         method: local
   analytics:
      mode: Inprocess

orbital:

pac4j:
   callback:
      path: /saml
   logout:
      path: /api/saml/logout

logging:
   level:

      org.springframework: WARN
      com.netflix.discovery.InstanceInfoReplicator: ERROR

      #       These two netflix loggers are REALLY noisy - it logs errors on startup, complaining it can't connect .. generally those errors are ignorable
      #        But, in some cases we may care -- so consider turning this back on.
      com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient: OFF
      com.netflix.discovery.DiscoveryClient: OFF
      org.apache.http: OFF
      com.netflix: WARN
      com.hazelcast: WARN
      io.vyne: INFO
#      io.vyne.query.chat: DEBUG
      #       Enable this to get graph debug schemas:
      #      io.vyne.query.GraphSearcher: TRACE
      #      io.vyne.query: DEBUG
      org.apache.catalina: WARN
      # AdminClientConfig is used for testing connections,
      # and gets really noisy.
      org.apache.kafka.clients.admin: WARN
      org.apache.kafka.common.metrics: WARN
      org.apache.kafka.common.utils: WARN
      org.apache.kafka.common.security.authenticator: WARN
      org.apache.kafka.clients.NetworkClient: ERROR

      #     Enable to see request / response logging
#      io.orbital.station.RequestLoggingFilter: TRACE

      # Unfortunately, this is really really noisy when we try to test
      # kafka connections, that have failed
   config: classpath:logback-spring.xml
#      org.apache.kafka.clients.NetworkClient: ERROR
