spring:
   application:
      name: pipeline-runner
   main:
      web-application-type: reactive
   codec:
      max-in-memory-size: 100MB

server:
   port: 9610

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000

eureka:
   uri: http://127.0.0.1:8761
   client:
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5

vyne:
   queryService:
      name: query-service
   caskService:
      name: cask
   queryServiceUrl: http://${vyne.queryService.name}
   schema:
        publicationMethod: DISTRIBUTED
        pollInterval: 5s
        publishRetryInterval: 3s
   graph:
      vyneGraphBuilderCache:
         baseSchemaCacheSize: 100
         graphWithFactTypesCacheSize: 100
         baseSchemaGraphCacheSize: 100
      vyneDiscoverGraphQuery:
         schemaGraphCacheSize: 5
         searchPathExclusionsCacheSize: 200000
   projection:
      distributionMode: LOCAL # One of [LOCAL | HAZELCAST] LOCAL = projections are performed on the instance process the query, HAZELCAST = distribute projection work to eligible members
      distributionPacketSize: 100 # Number of TypedInstances in a distributed workload - only applicable where distributionMode = HAZELCAST
      distributionRemoteBias: 10 # Number of nodes in the hazelcast cluster before work is preferentially distributed to remote nodes

   hazelcast:
      enabled: false # Enable or disable starting a hazelcast cluster
      discovery: MULTICAST # One of aws/multicast/swarm
      memberTag: vyne-query-service # Member tags allow delegation of responsibilities
      eurekaUri: http://127.0.0.1:8761/eureka/
