spring:
   application:
      name: pipeline-runner

server:
   port: 9610

service:
   cask:
      name: cask

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000

eureka:
   uri: http://127.0.0.1:9022
   client:
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5

vyne:
   queryServiceUrl: http://query-service
   schema:
        publicationmethod: REMOTE
        pollInterval: 5s
        publishRetryInterval: 3s
