<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <parent>
      <artifactId>platform</artifactId>
      <groupId>com.orbitalhq</groupId>
      <version>0.37.0-SNAPSHOT</version>
   </parent>
   <modelVersion>4.0.0</modelVersion>

   <artifactId>vyne-spring-http</artifactId>

   <licenses>
      <license>
         <name>The Apache Software License, Version 2.0</name>
         <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      </license>
   </licenses>

   <properties>
      <ayza.version>10.0.3</ayza.version>
   </properties>

   <description>Small library containing the HTTP interactions for Vyne that depend on Spring.  Exists to allow Vyne to have spring dependencies at test time, but not at compile time
   </description>
   <dependencies>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>auth-tokens</artifactId>
         <version>${project.version}</version>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>vyne-core-types</artifactId>
         <version>${project.version}</version>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>schema-consumer-api</artifactId>
         <version>${project.version}</version>
      </dependency>
      <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-webflux</artifactId>
      </dependency>
      <dependency>
         <groupId>io.github.openfeign</groupId>
         <artifactId>feign-core</artifactId>
      </dependency>
      <dependency>
         <groupId>org.springframework.security</groupId>
         <artifactId>spring-security-oauth2-client</artifactId>
      </dependency>

      <dependency>
         <groupId>io.github.hakky54</groupId>
         <artifactId>ayza</artifactId>
         <version>${ayza.version}</version>
      </dependency>

      <dependency>
         <groupId>io.github.hakky54</groupId>
         <artifactId>ayza-for-netty</artifactId>
         <version>${ayza.version}</version>
      </dependency>
      <!-- https://github.com/wiremock/wiremock/issues/2395
      Have to use wiremock-standalone with spring boot 12 -->
      <dependency>
         <groupId>org.wiremock</groupId>
         <artifactId>wiremock-standalone</artifactId>
         <version>3.4.2</version>
         <scope>test</scope>
      </dependency>
   </dependencies>

</project>
