package com.orbitalhq.connectors.nosql.mongodb

import com.orbitalhq.models.DataSourceUpdater
import com.orbitalhq.models.TypedInstance
import com.orbitalhq.query.QueryContextEventDispatcher
import com.orbitalhq.schema.api.SchemaProvider
import com.orbitalhq.schemas.Parameter
import com.orbitalhq.schemas.QueryOptions
import com.orbitalhq.schemas.RemoteOperation
import com.orbitalhq.schemas.Service
import com.orbitalhq.schemas.fqn
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.reactive.asFlow
import mu.KotlinLogging

private val logger = KotlinLogging.logger { }
class MongoMutatingQueryInvoker(
   connectionFactory: MongoConnectionFactory,
   schemaProvider: SchemaProvider
): MongoBaseInvoker(connectionFactory, schemaProvider) {

   suspend fun invoke(
      service: Service,
      operation: RemoteOperation,
      parameters: List<Pair<Parameter, TypedInstance>>,
      eventDispatcher: QueryContextEventDispatcher,
      queryId: String,
      queryOptions: QueryOptions
   ): Flow<TypedInstance> {
      val schema = schemaProvider.schema

      require(operation.parameters.size == 1) { "Operations annotated with ${MongoConnector.Annotations.UpsertOperationAnnotationName} should accept exactly one type" }
      val inputType = operation.parameters.single().type.let { type -> type.collectionType ?: type }
      require(inputType.hasMetadata(MongoConnector.Annotations.Collection.NAME.fqn()))
      { "The input type into an ${MongoConnector.Annotations.UpsertOperationAnnotationName} operation should be a type with a ${MongoConnector.Annotations.Collection.NAME.fqn()} annotation" }

      val (param, input) = parameters.singleOrNull()
         ?: error("Expected a single parameter, but received ${parameters.size}")
      val collectionName = inputType.taxiType.collectionNameOrTypeName()

      val (connectionConfig, reactiveMongoTemplate) = getConnectionConfigAndTemplate(service)
      val recordToWrite = parameters[0].second
      val documentMap = typedInstanceToMap(recordToWrite)
      val upsertDefinition =  MongoCriteriaGenerator.upsertFor(recordToWrite, documentMap)

     val upsertMono = if (upsertDefinition == null) {
         reactiveMongoTemplate.save(documentMap, collectionName)
      } else {
         reactiveMongoTemplate.upsert(upsertDefinition.first, upsertDefinition.second, collectionName).map { documentMap}
      }
      return upsertMono
         .elapsed()
         .map { durationAndData ->
            val duration = durationAndData.t1
            logger.info { "Mongo Upsert call completed in ${duration}ms "}
            val data = durationAndData.t2
            val operationResult = buildOperationResult(
               service,
               operation,
               listOf( input),
               "upsert",
               connectionConfig.connectionString.hosts.joinToString(),
               java.time.Duration.ofMillis(duration),
               recordCount = 1
            )
            eventDispatcher.reportRemoteOperationInvoked(operationResult, queryId)
            val resultTypedInstance =  mapToTypedInstance(data,inputType, schema,  operationResult.asOperationReferenceDataSource())
            DataSourceUpdater.update(resultTypedInstance, operationResult.asOperationReferenceDataSource())
         }.asFlow()

   }
}

/**
 * The difference between insert and save operations is that a save operation performs an insert if the object is not already present.
 * When inserting or saving, if the Id property is not set, the assumption is that its value will be auto-generated by the database.
 * Consequently, for auto-generation of an ObjectId to succeed,
 * the type of the Id property or field in your class must be a String, an ObjectId, or a BigInteger.
 */
