package com.orbitalhq.copilot

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo


@JsonTypeInfo(
   use = JsonTypeInfo.Id.NAME,
   include = JsonTypeInfo.As.PROPERTY,
   property = "kind"
)
@JsonSubTypes(
   JsonSubTypes.Type(value = ComponentMetadata::class, name = "component"),
   JsonSubTypes.Type(value = TaskDetails::class, name = "task"),
   JsonSubTypes.Type(value = EmptyEventData::class, name = "empty")
)
interface ChatEventData {
   companion object {
      val EMPTY = EmptyEventData()
   }
}


class EmptyEventData : ChatEventData {

}

/**
 * Untyped placeholder for passing data from MDX-ish
 * components generated by the chat.
 * We can't be 100% confident that the LLM will always generate the right stuff,
 * so we're leaving this as a map.
 *
 * We won't fail parsing, but might render slightly incorrectly.
 */
data class ComponentMetadata(
   val metadata: Map<String, Any>
) : ChatEventData {
   companion object {
      val EMPTY = ComponentMetadata(emptyMap())
   }
}


/**
 * Chat event metadata for tool and agent based messages.
 */
data class TaskDetails(
   val agentName: String,
   val taskDescription: String,
   val id: String,
   val eventStreamKind: EventStreamKind
) : ChatEventData

data class ChatEvent(
   val kind: ChatEventKind,
   val text: String?,
   val data: ChatEventData,
   val id: String,
   val role: ChatMessageRole = ChatMessageRole.assistant,
   // This is primarily for sorting events, which is why
   // I'm not using an Instant etc
   val timestamp: Long = System.currentTimeMillis(),
   // The triggering messageId that this event relates to, if part of a user
   // stream. Required for resubmitting messages
   val triggeringUserMessageId: String? = null
)



enum class ChatEventKind {
   AGENT_START,
   AGENT_STOP,
   TOOL_START,
   TOOL_STOP,
   MESSAGE,

   // Custom MDX-specific tags
   PLAN_START,
   PLAN_STOP,
   CODE_BLOCK_START,
   CODE_BLOCK_STOP,

   // Sent at the end when this specific conversation stream has ended
   STREAM_END

}
enum class EventStreamKind(
   val startEventKind: ChatEventKind,
   val stopEventKind: ChatEventKind
) {
   Agent(ChatEventKind.AGENT_START, ChatEventKind.AGENT_STOP),
   Tool(ChatEventKind.TOOL_START, ChatEventKind.TOOL_STOP)
}
