server:
  port: 9030
spring:
  application:
    name: trade-thresholds
vyne:
   schemaStore:
      name: discovery
   schema:
      name: trade-thresholds
      version: 0.1.0
logging:
  level:
      io.vyne: DEBUG
      io.osmosis: DEBUG
ribbon:
   restclient:
      enabled: true
   ServerListRefreshInterval: 1000
