management:
   endpoint:
      metrics:
         enabled: true
   endpoints:
      web:
         exposure:
            include: '*'

spring:
   datasource:
      url: "jdbc:postgresql://localhost:5432/voyager"
      username: "vynedb"
      password: "vynedb"
      driverClassName: org.postgresql.Driver
