server:
   port: 9500
   http2:
      enabled: true
   compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 1024
   error:
      include-message: always

hubspot:
   api:
      url: https://api.hubapi.com
      auth-token:
   subscriptions:
      voyager-updates-id:
      general-marketing:

spring:
   flyway:
      enabled: true
      url: ${spring.datasource.url}
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}
      locations: classpath:postgres

   datasource:
      url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/voyager"
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver: "org.postgresql.Driver"
      driverClassName: org.postgresql.Driver


management:
   endpoints:
      web:
         exposure:
            include: health
         base-path: /api/actuator
