server:
   port: 8088

spring:
   datasource:
      username: sa
      url: jdbc:h2:mem:authdb

keycloak:
   server:
      contextPath: /auth
      adminUser:
         username: vyneAdmin
         password: vyne
      realmImportFile: vyne-realm.json
      realmUsers:
         -
            username: marty
            email: marty@vyne.co
            password: test
         -
            username: serhat
            email: serhat@vyne.co
            password: test
