<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <parent>
      <groupId>com.orbitalhq</groupId>
      <artifactId>platform</artifactId>
      <version>0.36.0-M12</version>
   </parent>

   <artifactId>history-persistence</artifactId>


   <dependencies>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>vyne-history-core</artifactId>
         <version>${project.version}</version>
      </dependency>
      <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-data-jpa</artifactId>
         <!--
         https://github.com/spring-projects/spring-data-jpa/issues/2989#issuecomment-1997398619
         Spring Boot 3.2 came with a new Sql Parser built in - jsqlparser which is used
         to parse native queries.
         However, it's incomplete, and can't handle things like Postgres UPSERT statements with
         multiple ON CONFLICT params, which is what we use.
         https://github.com/JSQLParser/JSqlParser/issues/1820

         There's also reports of high CPU as the query gets parsed repeatedly.
         Excluding the dependency as reported on Github, since we don't seem to get any actual
         value from it.
         -->
<!--         <exclusions>-->
<!--            <exclusion>-->
<!--               <groupId>com.github.jsqlparser</groupId>-->
<!--               <artifactId>jsqlparser</artifactId>-->
<!--            </exclusion>-->
<!--         </exclusions>-->
      </dependency>


      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>vyne-spring</artifactId>
         <version>0.36.0-M12</version>
      </dependency>
      <dependency>
         <groupId>io.projectreactor</groupId>
         <artifactId>reactor-test</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>org.jetbrains.kotlinx</groupId>
         <artifactId>kotlinx-coroutines-test</artifactId>
         <scope>test</scope>
      </dependency>
   </dependencies>
</project>
