taxi:
   schema-local-storage: /path/to/taxonomy
   schema-recompile-interval-seconds: 3

spring:
   application:
      name: schema-server
eureka:
   uri: http://127.0.0.1:8761
   client:
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5
vyne:
   schema:
      name: ${spring.application.name}
      version: 0.1.0
      publicationMethod: REMOTE
      pollInterval: 5s
      publishRetryInterval: 3s

   hazelcast:
      enabled: false # Enable or disable starting a hazelcast cluster
      discovery: multicast # One of aws/multicast/swarm
      memberTag: vyne-query-service # Member tags allow delegation of responsibilities

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000

server:
   port: 9305

# Actuators + prometheus metrics configuration

management.endpoints.web.base-path: /api/actuator
management:
   metrics:
      export:
         prometheus:
            enabled: false
         influx:
            enabled: false
         elastic:
            enabled: false
         jmx:
            enabled: false
         graphite:
            enabled: false
         datadog:
            enabled: false
         dynatrace:
            enabled: false

   endpoint:
      metrics:
         enabled: true
      prometheus:
         enabled: false

   endpoints:
      web:
         exposure:
            include: prometheus,metrics,info,health

