taxi:
   schema-recompile-interval-seconds: 3

spring:
   main:
      banner-mode: off
   application:
      name: schema-server
   codec:
      max-in-memory-size: 1024MB
eureka:
   uri: http://127.0.0.1:8761
   client:
      enabled: false
      registryFetchIntervalSeconds: 1
      initialInstanceInfoReplicationIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${eureka.uri}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 2
      leaseExpirationDurationInSeconds: 5
      metadata-map:
         vyne-schema-server-port: ${vyne.schema.server.port}
vyne:
   schema:
      server:
         port: 7655

   hazelcast:
      enabled: false # Enable or disable starting a hazelcast cluster
      discovery: multicast # One of aws/multicast/swarm
      memberTag: schema-server # Member tags allow delegation of responsibilities
      eurekaUri: http://127.0.0.1:8761/eureka/

feign:
   client:
      config:
         default:
            connectTimeout: 5000
            readTimeout: 5000

server:
   port: 9305
   error:
      include-message: always

# Actuators + prometheus metrics configuration

management.endpoints.web.base-path: /api/actuator
management:
   metrics:
      export:
         prometheus:
            enabled: false
         influx:
            enabled: false
         elastic:
            enabled: false
         jmx:
            enabled: false
         graphite:
            enabled: false
         datadog:
            enabled: false
         dynatrace:
            enabled: false

   endpoint:
      metrics:
         enabled: true
      prometheus:
         enabled: false

   endpoints:
      web:
         exposure:
            include: prometheus,metrics,info,health

#logging:
#   level:
#      io.netty: DEBUG
#      org.apache: DEBUG
#      org.springframework: DEBUG
#      org.springframework.web.reactive: DEBUG
#      org.springframework.http.server.reactive: DEBUG

