<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <parent>
      <groupId>com.orbitalhq</groupId>
      <artifactId>platform</artifactId>
      <version>0.34.0-SNAPSHOT</version>
   </parent>

   <artifactId>nebula-support</artifactId>

   <properties>
      <maven.compiler.source>21</maven.compiler.source>
      <maven.compiler.target>21</maven.compiler.target>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
      <ktor.version>2.3.12</ktor.version>
   </properties>

   <dependencies>
      <dependency>
         <groupId>com.orbitalhq.nebula</groupId>
         <artifactId>nebula-api</artifactId>
         <version>1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
         <groupId>io.rsocket.kotlin</groupId>
         <artifactId>rsocket-ktor-client-jvm</artifactId>
         <version>0.16.0</version>
      </dependency>
      <dependency>
         <groupId>io.ktor</groupId>
         <artifactId>ktor-client-cio-jvm</artifactId>
         <version>${ktor.version}</version>
      </dependency>
      <dependency>
         <groupId>io.ktor</groupId>
         <artifactId>ktor-client-content-negotiation-jvm</artifactId>
         <version>${ktor.version}</version>
      </dependency>
      <dependency>
         <groupId>io.ktor</groupId>
         <artifactId>ktor-serialization-jackson-jvm</artifactId>
         <version>${ktor.version}</version>
      </dependency>
      <dependency>
         <groupId>io.ktor</groupId>
         <artifactId>ktor-client-core-jvm</artifactId>
         <version>${ktor.version}</version>
      </dependency>

      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>schema-consumer-api</artifactId>
         <version>${project.version}</version>
      </dependency>
      <dependency>
         <groupId>org.springframework</groupId>
         <artifactId>spring-context</artifactId>
      </dependency>
      <dependency>
         <groupId>org.springframework</groupId>
         <artifactId>spring-web</artifactId>
      </dependency>
      <dependency>
         <groupId>io.projectreactor</groupId>
         <artifactId>reactor-test</artifactId>
         <scope>test</scope>
      </dependency>

      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>schema-server-core</artifactId>
         <version>${project.version}</version>
         <scope>test</scope>
         <type>test-jar</type>
      </dependency>
      <dependency>
         <groupId>com.orbitalhq</groupId>
         <artifactId>schema-server-core</artifactId>
         <version>${project.version}</version>
      </dependency>
   </dependencies>

</project>
