server:
  port: 9023
spring:
  application:
    name: isic-lookup
vyne:
   schemaStore:
      name: discovery
   schema:
      name: isic-lookup
      version: 0.1.0
logging:
  level:
      io.vyne: DEBUG
      io.osmosis: DEBUG
ribbon:
   restclient:
      enabled: true
   ServerListRefreshInterval: 1000
